# Generated by Django 5.0.6 on 2024-05-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
    ]
