# Generated by Django 5.0.6 on 2024-05-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_city_lat_alter_city_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='lon',
            new_name='longitude',
        ),
    ]
